### ISSUE TITLE
Persist the task list between restarts

### ISSUE THREAD

**Issue by tadast** [tadast/dumbot#10]
Could use [PStore](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/pstore/rdoc/PStore.html) or something similar

**Comment by toreriklinnerud** [comment]
How about some cloud storage?

**Comment by tadast** [comment]
Too hot  :cloud: :high_brightness: :cloud: :cloud:

**Comment by davidgriffiths** [comment]
We could hire that google guy to sort us out with some tape drives?

**Comment by toreriklinnerud** [comment]
tada https://github.com/tadast/dumbot/commit/007672a04b569837e4c714732a8aadbb2c0ea416
